name: traincellpose
channels:
  - conda-forge
  - defaults
dependencies:
  - python<=3.9
  - scipy
  - h5py
  - imageio
  - opencv
  - fastai::opencv-python-headless # -c fastai, is it needed?
  - pyyaml
  - tifffile
  - ome-zarr
  - napari
  - magicgui
  - napari-ome-zarr
  - pyqt
  - imageio-ffmpeg
  # paquo deps
  - jpype1>=1.0.1
  - dynaconf>=3,!=3.1.0,!=3.1.7
  - ome-types  # [ WITH_OME ]
  - shapely
  # New zarr tools from Andreas
  - dask-image
  - dask

