name: spacem_annotator
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - pandas
  - scipy
  - h5py
  - imageio
  - opencv
  - napari
  - magicgui # Probably already included in napari
  - pyqt
  - abailoni::speedrun
  - abailoni::paquo #  QuPath dependencies: TODO: create a QuPath flag?
  - ome-zarr
    # For cellpose
  - numba
