name: traincellpose
channels:
  - conda-forge
  - defaults
dependencies:
  - python<=3.9
  - scipy
  - h5py
  - imageio
  - opencv
  - pyyaml
  - tifffile
  - ome-zarr
  - napari
  - magicgui
  - pyqt
  - abailoni::speedrun
  - abailoni::paquo
