name: traincellpose
channels:
  - conda-forge
  - defaults
dependencies:
  - python<=3.9
  - scipy
  - h5py
  - imageio
  - opencv
  - fastai::opencv-python-headless # -c fastai, is it needed?
  - pyyaml
  - tifffile
  - ome-zarr
  - napari
  - napari-ome-zarr
  - magicgui
  - pyqt
  - imageio-ffmpeg
  - abailoni::speedrun
  - abailoni::paquo
##- # New zarr tools from Andreas
#  - dask-image
#  - dask
  # Tests, temp:
  - pytest-qt
  - pytest
  - napari[dev]


