package:
  name: traincellpose
  version: 0.2.0

source:
  path: ..

build:
  script: "pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  number: 1

requirements:
  build:
    - python {{ python }}
    - pip
  run:
    - python {{ python }}
    - scipy
    - h5py
    - imageio
    - opencv
    - speedrun
    - tifffile
    - ome-zarr
    - napari
    - magicgui
    - pyqt
    - paquo

test:
  imports:
    - traincellpose
    - traincellpose.core
    - traincellpose.napari_gui.roi_selection
#    - paquo #  QuPath dependency
  source_files:
    - tests/**/*.py
  commands:
    - python -m unittest discover -s test -v

about:
  home: https://github.com/abailoni/cellpose-training-gui
  license: MIT
