package:
  name: traincellpose
  version: 0.2.1

source:
  path: ..

build:
  script: "pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  number: 1

requirements:
  build:
    - python {{ python }}
    - pip
  run:
    - python {{ python }}
    - scipy
    - h5py
    - imageio
    - opencv
    - speedrun
    - tifffile
    - ome-zarr
    - napari >=0.4.16
    - magicgui
    - pyqt
    - paquo
    - napari-ome-zarr

test:
  imports:
    - traincellpose
    - traincellpose.core
    - traincellpose.napari_gui.roi_selection
#    - paquo #  QuPath dependency
  requires:
    - pip
    - pytest
    - napari[dev]
  source_files:
    - tests/**/*.py
  commands:
#    - python -m unittest discover -s test -v
    - pytest tests/

about:
  home: https://github.com/abailoni/cellpose-training-gui
  license: MIT
