name: ci

on:
  push:
    branches:
      - '*'

  pull_request:
    branches:
      - '*'

#  schedule:
#    - cron: '0 0 * * *'

#env:
#  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  build:

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            label: linux-64
            prefix: /usr/share/miniconda3/envs/my-env

#          - os: macos-latest
#            label: osx-64
#            prefix: /Users/runner/miniconda3/envs/my-env
#
#          - os: windows-latest
#            label: win-64
#            prefix: C:\Miniconda3\envs\my-env

    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniforge-variant: Mambaforge
            miniforge-version: latest
            activate-environment: my-env
            use-mamba: true

#      - name: Set cache date
#        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
#
#      - uses: actions/cache@v2
#        with:
#          path: ${{ matrix.prefix }}
#          key: ${{ matrix.label }}-conda-${{ hashFiles('environment.yml') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
#        id: cache
#          mamba env update -n my-env -f environment.yml

      - name: Update environment
        run:  | 
              pip install --no-cache-dir -r ./requirements.txt -r ./requirements-dev.txt
              mamba list
              mamba info --all
#        if: steps.cache.outputs.cache-hit != 'true'
#
#      - name: Install PtAC (name of my own python package)
#          run: |
#            python setup.py install
#            conda list
#            conda info --all

      - name: Run tests
        shell: bash -l {0}
        run: pytest ./tests
